name: axie_exploration
channels:
  - conda-forge
dependencies:
  - pandas
  - numpy
  - scipy
  - keras
  - scikit-learn
  - matplotlib
  - seaborn
  - psycopg2
  - setuptools
  - conda-pack
  - conda-tree
  - kedro
  - wheel
  - pbr
  - build
  - black 
  - ipykernel